## bugfix/core

* Now inserting a tuple with a wrong `id` field into the `\_priv` space returns
  the correct error (gh-6295).

